# reference: https://www.youtube.com/watch?v=S6j4VGMD3Y8&list=PLQH1-k79HB396mS8xRQ5gih5iqkQw-4aV&index=1&pp=iAQB
# dev
version: "1"
services:
  #nginx
  web:
    image: nginx:latest
    ports:
      - "30303:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  #php
  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - /var/www/html/vendor
      - ./app:/var/www/html
  #mysql
  db:
    image: mysql:8.0
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - "30304:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: docker-php
      #  redis: