services:
  # nginx
  web:
    image: nginx:1.27.4
    ports:
      - "${WEB_OUTER_PORT}:${WEB_PORT}"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  # php
  app:
    build:
      dockerfile: ./php/Dockerfile
      target: app_dev
    volumes:
      - /var/www/html/vendor
      - ./:/var/www/html
      - ./docker/nginx/log:/var/log/nginx
  # mysql
  db:
    image: mysql:8.0
    volumes:
      - ./docker/mysql/mysqldata:/var/lib/mysql
      - ./docker/mysql/log:/var/log/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "${DB_OUTER_PORT}:${DB_PORT}"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

  # redis
