services:
  # nginx
  web:
    image: nginx:1.27.4
    ports:
      - "10100:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  # php
  app:
    build:
      dockerfile: ./php/Dockerfile
      target: app_dev
    volumes:
      - /var/www/html/vendor
      - ./app:/var/www/html
      - ./nginx/log:/var/log/nginx
  # mysql
  db:
    image: mysql:8.0
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  # redis
