version: "3"

services:
  webserver:
    build: .
    ports:
      - "12345:80"
    volumes:
      - .:/var/www/html
      - ./docker/log:/var/log/apache2/
    command: sh -c "./start.sh && apachectl -D FOREGROUND"
    restart: always
