version: "1"
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 0.0.0.0:7070:3306
    environment:
      MYSQL_ROOT_PASSWORD: "asdzxcasdad"
      MYSQL_DATABASE: "abcd"
      MYSQL_USER: "mysql-normal-user"
      MYSQL_PASSWORD: "asdzxcasdad"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/log:/var/log/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d