name: MyService
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 컴포저 의존성 설치
        working-directory: ./nginx-php-fpm-xdebug-actions/app
        run: composer install --prefer-dist
      - name: 테스트
        working-directory: ./nginx-php-fpm-xdebug-actions/app
        run: composer test
